Date: Thu, 21 Mar 2019 06:59:05 -0700 (PDT)
From: Adrian Jackson <adrianj...@gmail.com>
To: singularity <singu...@lbl.gov>
Message-Id: <61832310-7d6e-45ae-bf69-2bc68cae7600@lbl.gov>
In-Reply-To: <3bc7c413-38a5-4354-8105-894588905ae6@lbl.gov>
References: <3bc7c413-38a5-4354-8105-894588905ae6@lbl.gov>
Subject: Re: Calling parallel python from singularity
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_235_2134383773.1553176745812"

------=_Part_235_2134383773.1553176745812
Content-Type: multipart/alternative; 
	boundary="----=_Part_236_624705586.1553176745813"

------=_Part_236_624705586.1553176745813
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

This was caused by a mismatch in the MPI used for Python and mpi4py and the 
MPI being used external to the container.

------=_Part_236_624705586.1553176745813
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<div dir="ltr">This was caused by a mismatch in the MPI used for Python and mpi4py and the MPI being used external to the container.<br></div>
------=_Part_236_624705586.1553176745813--

------=_Part_235_2134383773.1553176745812--
