Date: Thu, 19 Oct 2017 19:08:44 -0700 (PDT)
From: Bili Dong <qobi...@gmail.com>
To: singularity <singu...@lbl.gov>
Message-Id: <6b519f4e-6afc-4164-a1bf-d8f3eb8fd372@lbl.gov>
Subject: Issue with the Miniconda Docker image or using Conda in Singularity
 in general
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_4005_1655808466.1508465324165"

------=_Part_4005_1655808466.1508465324165
Content-Type: multipart/alternative; 
	boundary="----=_Part_4006_825150610.1508465324165"

------=_Part_4006_825150610.1508465324165
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello all,

I'm writing to request some help on an issue I encountered that I couldn't 
solve by myself.

I'm using Singularity 2.4. To reproduce the error, do the following:

```
singularity shell docker://continuumio/miniconda3:4.3.27
```

then within Singularity, do:

```
python -c "import multiprocessing as mp; mp.Queue()"
```

which results in the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 102, in 
Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 42, in 
__init__
    self._rlock = ctx.Lock()
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 67, in 
Lock
    return Lock(ctx=self.get_context())
  File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 163, 
in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 60, 
in __init__
    unlink_now)
FileNotFoundError: [Errno 2] No such file or directory
```

The same code would work inside a Docker container. So I expected it to 
work in the corresponding Singularity container too. But it doesn't.

Thanks very much for your time!

Best,
Bili

------=_Part_4006_825150610.1508465324165
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hello all,<div><br></div><div>I&#39;m writing to request s=
ome help on an issue I encountered that I couldn&#39;t solve by myself.<br>=
<div><br></div><div>I&#39;m using Singularity 2.4. To reproduce the error, =
do the following:<div><br></div><div><font face=3D"courier new, monospace">=
```</font></div><div><font face=3D"courier new, monospace">singularity shel=
l=C2=A0docker://continuumio/miniconda3:4.3.27</font></div><div><font face=
=3D"courier new, monospace">```</font></div><div><br></div><div>then within=
 Singularity, do:</div><div><br></div><div><font face=3D"courier new, monos=
pace">```</font></div><div><font face=3D"courier new, monospace">python -c =
&quot;import multiprocessing as mp; mp.Queue()&quot;</font></div><div><font=
 face=3D"courier new, monospace">```</font></div><div><br></div><div>which =
results in the following error:</div><div><br></div><div><font face=3D"cour=
ier new, monospace">```</font></div><div><font face=3D"courier new, monospa=
ce">Traceback (most recent call last):</font></div><div><font face=3D"couri=
er new, monospace">=C2=A0 File &quot;&lt;string&gt;&quot;, line 1, in &lt;m=
odule&gt;</font></div><div><font face=3D"courier new, monospace">=C2=A0 Fil=
e &quot;/opt/conda/lib/python3.6/multiprocessing/context.py&quot;, line 102=
, in Queue</font></div><div><font face=3D"courier new, monospace">=C2=A0 =
=C2=A0 return Queue(maxsize, ctx=3Dself.get_context())</font></div><div><fo=
nt face=3D"courier new, monospace">=C2=A0 File &quot;/opt/conda/lib/python3=
.6/multiprocessing/queues.py&quot;, line 42, in __init__</font></div><div><=
font face=3D"courier new, monospace">=C2=A0 =C2=A0 self._rlock =3D ctx.Lock=
()</font></div><div><font face=3D"courier new, monospace">=C2=A0 File &quot=
;/opt/conda/lib/python3.6/multiprocessing/context.py&quot;, line 67, in Loc=
k</font></div><div><font face=3D"courier new, monospace">=C2=A0 =C2=A0 retu=
rn Lock(ctx=3Dself.get_context())</font></div><div><font face=3D"courier ne=
w, monospace">=C2=A0 File &quot;/opt/conda/lib/python3.6/multiprocessing/sy=
nchronize.py&quot;, line 163, in __init__</font></div><div><font face=3D"co=
urier new, monospace">=C2=A0 =C2=A0 SemLock.__init__(self, SEMAPHORE, 1, 1,=
 ctx=3Dctx)</font></div><div><font face=3D"courier new, monospace">=C2=A0 F=
ile &quot;/opt/conda/lib/python3.6/multiprocessing/synchronize.py&quot;, li=
ne 60, in __init__</font></div><div><font face=3D"courier new, monospace">=
=C2=A0 =C2=A0 unlink_now)</font></div><div><font face=3D"courier new, monos=
pace">FileNotFoundError: [Errno 2] No such file or directory</font></div><d=
iv><font face=3D"courier new, monospace">```</font></div><div><br></div><di=
v>The same code would work inside a Docker container. So I expected it to w=
ork in the corresponding Singularity container too. But it doesn&#39;t.</di=
v><div><br></div><div>Thanks very much for your time!</div></div></div><div=
><br></div><div>Best,</div><div>Bili</div></div>
------=_Part_4006_825150610.1508465324165--

------=_Part_4005_1655808466.1508465324165--
