Date: Thu, 19 Oct 2017 20:30:33 -0700 (PDT)
From: Bili Dong <qobi...@gmail.com>
To: singularity <singu...@lbl.gov>
Message-Id: <8e941d09-0643-4f46-adb7-8a20baf2ce7b@lbl.gov>
In-Reply-To: <799b041c-65cd-4e84-9b3a-46a8ac3fcc83@lbl.gov>
References: <6b519f4e-6afc-4164-a1bf-d8f3eb8fd372@lbl.gov>
 <CAAQzouPgh9hmFXM6WSjtpLBcjLSPYYymRKXyfwuCirPTyNO+Fg@mail.gmail.com>
 <799b041c-65cd-4e84-9b3a-46a8ac3fcc83@lbl.gov>
Subject: Re: [Singularity] Issue with the Miniconda Docker image or using
 Conda in Singularity in general
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_4214_1915062013.1508470233927"

------=_Part_4214_1915062013.1508470233927
Content-Type: multipart/alternative; 
	boundary="----=_Part_4215_1003443546.1508470233927"

------=_Part_4215_1003443546.1508470233927
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

So this is a known issue, and the current workaround is to add /run as a 
bind path, like this:

```
singularity shell -B /run docker://continuumio/miniconda3:4.3.27
```

See the following links for previous discussions:
https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/71MhNumuMbs/discussion
https://github.com/singularityware/singularity/issues/875

On Thursday, October 19, 2017 at 8:11:58 PM UTC-7, Bili Dong wrote:
>
> Thanks Chris. This does look like the same issue.
>
> Best,
> Bili
>
> On Thursday, October 19, 2017 at 8:04:33 PM UTC-7, Chris Filo Gorgolewski 
> wrote:
>>
>> This seems to be related: 
>> https://github.com/poldracklab/fmriprep/issues/780
>>
>> Best,
>> Chris
>>
>> On Thu, Oct 19, 2017 at 7:08 PM, Bili Dong <qo...@gmail.com> wrote:
>>
>>> Hello all,
>>>
>>> I'm writing to request some help on an issue I encountered that I 
>>> couldn't solve by myself.
>>>
>>> I'm using Singularity 2.4. To reproduce the error, do the following:
>>>
>>> ```
>>> singularity shell docker://continuumio/miniconda3:4.3.27
>>> ```
>>>
>>> then within Singularity, do:
>>>
>>> ```
>>> python -c "import multiprocessing as mp; mp.Queue()"
>>> ```
>>>
>>> which results in the following error:
>>>
>>> ```
>>> Traceback (most recent call last):
>>>   File "<string>", line 1, in <module>
>>>   File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 102, 
>>> in Queue
>>>     return Queue(maxsize, ctx=self.get_context())
>>>   File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 42, in 
>>> __init__
>>>     self._rlock = ctx.Lock()
>>>   File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 67, 
>>> in Lock
>>>     return Lock(ctx=self.get_context())
>>>   File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 
>>> 163, in __init__
>>>     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
>>>   File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 
>>> 60, in __init__
>>>     unlink_now)
>>> FileNotFoundError: [Errno 2] No such file or directory
>>> ```
>>>
>>> The same code would work inside a Docker container. So I expected it to 
>>> work in the corresponding Singularity container too. But it doesn't.
>>>
>>> Thanks very much for your time!
>>>
>>> Best,
>>> Bili
>>>
>>> -- 
>>> You received this message because you are subscribed to the Google 
>>> Groups "singularity" group.
>>> To unsubscribe from this group and stop receiving emails from it, send 
>>> an email to singu...@lbl.gov.
>>>
>>
>>
------=_Part_4215_1003443546.1508470233927
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">So this is a known issue, and the current workaround is to=
 add /run as a bind path, like this:<div><br></div><div><div><font face=3D"=
courier new, monospace">```</font></div><div><font face=3D"courier new, mon=
ospace">singularity shell -B /run docker://continuumio/<wbr>miniconda3:4.3.=
27</font></div><div><font face=3D"courier new, monospace">```</font></div><=
/div><div><font face=3D"courier new, monospace"><br></font></div><div><font=
 face=3D"arial, sans-serif">See the following links for previous discussion=
s:</font></div><div><a href=3D"https://groups.google.com/a/lbl.gov/forum/#!=
topic/singularity/71MhNumuMbs/discussion"><span style=3D"font-family: arial=
, sans-serif;">https://groups.google.com/a/lbl.gov/forum/#!topic/singularit=
y/71MhNumuMbs/discussion</span><br></a></div><div><div><font face=3D"arial,=
 sans-serif"><a href=3D"https://github.com/singularityware/singularity/issu=
es/875">https://github.com/singularityware/singularity/issues/875</a></font=
></div></div><div><br>On Thursday, October 19, 2017 at 8:11:58 PM UTC-7, Bi=
li Dong wrote:<blockquote class=3D"gmail_quote" style=3D"margin: 0;margin-l=
eft: 0.8ex;border-left: 1px #ccc solid;padding-left: 1ex;"><div dir=3D"ltr"=
>Thanks Chris. This does look like the same issue.<div><br></div><div>Best,=
</div><div>Bili<br><br>On Thursday, October 19, 2017 at 8:04:33 PM UTC-7, C=
hris Filo Gorgolewski wrote:<blockquote class=3D"gmail_quote" style=3D"marg=
in:0;margin-left:0.8ex;border-left:1px #ccc solid;padding-left:1ex"><div di=
r=3D"ltr">This seems to be related:=C2=A0<a href=3D"https://github.com/pold=
racklab/fmriprep/issues/780" rel=3D"nofollow" target=3D"_blank" onmousedown=
=3D"this.href=3D&#39;https://www.google.com/url?q\x3dhttps%3A%2F%2Fgithub.c=
om%2Fpoldracklab%2Ffmriprep%2Fissues%2F780\x26sa\x3dD\x26sntz\x3d1\x26usg\x=
3dAFQjCNHw0gZCuBiDzuYOna29GJ8IbaoyPA&#39;;return true;" onclick=3D"this.hre=
f=3D&#39;https://www.google.com/url?q\x3dhttps%3A%2F%2Fgithub.com%2Fpoldrac=
klab%2Ffmriprep%2Fissues%2F780\x26sa\x3dD\x26sntz\x3d1\x26usg\x3dAFQjCNHw0g=
ZCuBiDzuYOna29GJ8IbaoyPA&#39;;return true;">https://github.com/<wbr>poldrac=
klab/fmriprep/issues/<wbr>780</a></div><div><br clear=3D"all"><div><div><di=
v dir=3D"ltr">Best,<div>Chris</div></div></div></div>
<br><div class=3D"gmail_quote">On Thu, Oct 19, 2017 at 7:08 PM, Bili Dong <=
span dir=3D"ltr">&lt;<a rel=3D"nofollow">qo...@gmail.com</a>&gt;</span> wro=
te:<br><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-=
left:1px #ccc solid;padding-left:1ex"><div dir=3D"ltr">Hello all,<div><br><=
/div><div>I&#39;m writing to request some help on an issue I encountered th=
at I couldn&#39;t solve by myself.<br><div><br></div><div>I&#39;m using Sin=
gularity 2.4. To reproduce the error, do the following:<div><br></div><div>=
<font face=3D"courier new, monospace">```</font></div><div><font face=3D"co=
urier new, monospace">singularity shell=C2=A0docker://continuumio/<wbr>mini=
conda3:4.3.27</font></div><div><font face=3D"courier new, monospace">```</f=
ont></div><div><br></div><div>then within Singularity, do:</div><div><br></=
div><div><font face=3D"courier new, monospace">```</font></div><div><font f=
ace=3D"courier new, monospace">python -c &quot;import multiprocessing as mp=
; mp.Queue()&quot;</font></div><div><font face=3D"courier new, monospace">`=
``</font></div><div><br></div><div>which results in the following error:</d=
iv><div><br></div><div><font face=3D"courier new, monospace">```</font></di=
v><div><font face=3D"courier new, monospace">Traceback (most recent call la=
st):</font></div><div><font face=3D"courier new, monospace">=C2=A0 File &qu=
ot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;</font></div><div><font f=
ace=3D"courier new, monospace">=C2=A0 File &quot;/opt/conda/lib/python3.6/<=
wbr>multiprocessing/context.py&quot;, line 102, in Queue</font></div><div><=
font face=3D"courier new, monospace">=C2=A0 =C2=A0 return Queue(maxsize, ct=
x=3Dself.get_context())</font></div><div><font face=3D"courier new, monospa=
ce">=C2=A0 File &quot;/opt/conda/lib/python3.6/<wbr>multiprocessing/queues.=
py&quot;, line 42, in __init__</font></div><div><font face=3D"courier new, =
monospace">=C2=A0 =C2=A0 self._rlock =3D ctx.Lock()</font></div><div><font =
face=3D"courier new, monospace">=C2=A0 File &quot;/opt/conda/lib/python3.6/=
<wbr>multiprocessing/context.py&quot;, line 67, in Lock</font></div><div><f=
ont face=3D"courier new, monospace">=C2=A0 =C2=A0 return Lock(ctx=3Dself.ge=
t_context())</font></div><div><font face=3D"courier new, monospace">=C2=A0 =
File &quot;/opt/conda/lib/python3.6/<wbr>multiprocessing/synchronize.<wbr>p=
y&quot;, line 163, in __init__</font></div><div><font face=3D"courier new, =
monospace">=C2=A0 =C2=A0 SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=3Dctx)=
</font></div><div><font face=3D"courier new, monospace">=C2=A0 File &quot;/=
opt/conda/lib/python3.6/<wbr>multiprocessing/synchronize.<wbr>py&quot;, lin=
e 60, in __init__</font></div><div><font face=3D"courier new, monospace">=
=C2=A0 =C2=A0 unlink_now)</font></div><div><font face=3D"courier new, monos=
pace">FileNotFoundError: [Errno 2] No such file or directory</font></div><d=
iv><font face=3D"courier new, monospace">```</font></div><div><br></div><di=
v>The same code would work inside a Docker container. So I expected it to w=
ork in the corresponding Singularity container too. But it doesn&#39;t.</di=
v><div><br></div><div>Thanks very much for your time!</div></div></div><div=
><br></div><div>Best,</div><div>Bili</div></div><span><font color=3D"#88888=
8">

<p></p>

-- <br>
You received this message because you are subscribed to the Google Groups &=
quot;singularity&quot; group.<br>
To unsubscribe from this group and stop receiving emails from it, send an e=
mail to <a rel=3D"nofollow">singu...@lbl.gov</a>.<br>
</font></span></blockquote></div><br></div>
</blockquote></div></div></blockquote></div></div>
------=_Part_4215_1003443546.1508470233927--

------=_Part_4214_1915062013.1508470233927--
